[meta title:"Idyll Example: July 6th, 2017" description:"This example demonstrate some of the scroll effects" /]

[Header
  title:"Idyll Example: July 6th, 2017. Scroll"
  subtitle:"Welcome to Literasee, powered by Idyll"
  author:"dbetebenner"
  authorLink:"https://github.com/dbetebenner" /]

[var name:"randomSeed" value:0 /]

[Feature]

  [Waypoint onEnterView:`randomSeed=2`]
    A new markup language 
    for creating interactive 
    documents
  [/Waypoint]

  [Waypoint onEnterView:`randomSeed=0` ]
    Combine a lightweight 
    markup language and reactive 
    JavaScript components
  [/Waypoint]


  [Waypoint onEnterView:`randomSeed=1` ]
    Visit [link href:"https://idyll-lang.github.io/" text:"https://idyll-lang.github.io/" /]
    for more information
  [/Waypoint]

[/Feature]